### ISSUE TITLE
After copying cues from difficulty X to difficulty Y, prompt the user to load difficulty Y.

### ISSUE THREAD

**Issue by Bacon-Kevin** [octoberU/NotReaper#1]
After copying a higher difficulty to a lower one, I often start modifying the higher difficulty thinking it is the newly copied lower one. A prompt for the user to load the newly-made difficulty upon generation would prevent this PEBKAC error.

**Comment by octoberU** [comment]
Added,  it will be a part of this:
https://github.com/octoberU/NotReaper/projects/1#card-45366905
